version: '3'
services:
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./www/html:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOSTS=
  #     - PMA_USER=
  #     - PMA_PASSWORD=
  #   ports:
  #     - 8085:80